services:
  # Database
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - back
    command: ["--default-authentication-plugin=caching_sha2_password"]

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    env_file:
      - .env
    environment:
      PMA_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - back

  #Nest 
  nest:
    container_name: collectif-back
    image: collectif-back
    build:
      dockerfile: Dockerfile.nest
      context: .
    networks:
      - back
    depends_on:
      - mysql
    env_file:
      - .env
    restart: unless-stopped

  #Prisma studio
  prisma-studio:
    links:
      - nest
    depends_on:
      - nest
    image: prisma-studio
    container_name: prisma-studio
    build:
      context: .
      dockerfile: Dockerfile.studio
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - back
    volumes:
      - ./prisma:/app/prisma

networks:
  back:
    external: true 

volumes:
  db_data:
